default: &default
  adapter: postgresql
  encoding: utf8
  pool: 10
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>
  reconnect: true
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: "gamification_development"

test:
  <<: *default
  database: "gamification_test"

production:
  <<: *default
  database: "gamification"
